# Generated by Django 5.1.3 on 2025-02-12 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_type_food'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'غذا', 'verbose_name_plural': 'غذاها'},
        ),
    ]
